### ISSUE TITLE
Unable to load puppet

### ISSUE THREAD

**Issue by akerl** [halyard/halyard#100]
```
❯ boxen
Unable to load puppet. Please install it using native packages for your platform (eg .deb, .rpm, .dmg, etc).
puppet --version returned pid 73828 exit 1
/Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/source/git.rb:191:in `rescue in load_spec_files': https://github.com/halyard/boxen.git (at 2.8.0.akerl8@afa1336) is not yet checked out. Run `bundle install` first. (Bundler::GitError)
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/source/git.rb:188:in `load_spec_files'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/source/path.rb:92:in `local_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/source/git.rb:159:in `specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/lazy_specification.rb:53:in `__materialize__'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/spec_set.rb:90:in `block in materialize'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/spec_set.rb:87:in `map!'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/spec_set.rb:87:in `materialize'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/definition.rb:137:in `specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/definition.rb:182:in `specs_for'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/definition.rb:171:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/environment.rb:18:in `requested_specs'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/runtime.rb:13:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler.rb:92:in `setup'
	from /Library/Ruby/Gems/2.0.0/gems/bundler-1.11.1/lib/bundler/setup.rb:18:in `<top (required)>'
	from /opt/rubies/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /opt/rubies/2.2.3/lib/ruby/2.2.0/rubygems/core_ext/kernel_require.rb:54:in `require'
Can't run Puppet, fetching dependencies with librarian failed.
```

**Comment by akerl** [comment]
Transient error
