### ISSUE TITLE
Puppet librarian halyard-homebrew conflict

### ISSUE THREAD

**Issue by jaredledvina** [halyard/halyard#123]
```
[Librarian] Ruby Version: 2.0.0
[Librarian] Ruby Platform: universal.x86_64-darwin16
[Librarian] Rubygems Version: 2.0.14.1
[Librarian] Librarian Version: 0.6.3
[Librarian] Librarian Adapter: puppet
[Librarian] Librarian Adapter Version: 2.2.3
[Librarian] Project: /opt/halyard/repo
[Librarian] Specfile: Puppetfile
[Librarian] Lockfile: Puppetfile.lock
[Librarian] Git: /usr/local/bin/git
[Librarian] Git Version: 2.10.0
[Librarian] Git Environment Variables:
[Librarian]   (empty)
[Librarian] Pre-Cached Sources:
[Librarian] Post-Cached Sources:
[Librarian]   [:forge, "https://forgeapi.puppetlabs.com", {}]
[Librarian] Resolving halyard-halyard (= 0.0.3) <https://forgeapi.puppetlabs.com>
[Librarian]   Checking manifests
[Librarian]   Module halyard-halyard found versions: 0.0.3, 0.0.2, 0.0.1
[Librarian]     Checking halyard-halyard/0.0.3 <https://forgeapi.puppetlabs.com>
[Librarian]       Resolved halyard-halyard (= 0.0.3) <https://forgeapi.puppetlabs.com> at halyard-halyard/0.0.3 <https://forgeapi.puppetlabs.com>
[Librarian]   Resolved halyard-halyard (= 0.0.3) <https://forgeapi.puppetlabs.com>
[Librarian] Resolving halyard-repository (= 2.4.3) <https://forgeapi.puppetlabs.com>
[Librarian]   Checking manifests
[Librarian]   Module halyard-repository found versions: 2.4.3, 2.4.2
[Librarian]     Checking halyard-repository/2.4.3 <https://forgeapi.puppetlabs.com>
[Librarian]       Resolved halyard-repository (= 2.4.3) <https://forgeapi.puppetlabs.com> at halyard-repository/2.4.3 <https://forgeapi.puppetlabs.com>
[Librarian]   Resolved halyard-repository (= 2.4.3) <https://forgeapi.puppetlabs.com>
[Librarian] Resolving halyard-homebrew (= 1.13.3) <https://forgeapi.puppetlabs.com>
[Librarian]   Checking manifests
[Librarian]   Module halyard-homebrew found versions: 1.13.3, 1.13.2, 1.13.1
[Librarian]     Checking halyard-homebrew/1.13.3 <https://forgeapi.puppetlabs.com>
[Librarian]       Resolved halyard-homebrew (= 1.13.3) <https://forgeapi.puppetlabs.com> at halyard-homebrew/1.13.3 <https://forgeapi.puppetlabs.com>
[Librarian]   Resolved halyard-homebrew (= 1.13.3) <https://forgeapi.puppetlabs.com>
[Librarian] Resolving halyard-zsh (= 0.0.12) <https://forgeapi.puppetlabs.com>
[Librarian]   Checking manifests
[Librarian]   Module halyard-zsh found versions: 0.0.12, 0.0.11, 0.0.10, 0.0.9, 0.0.8
[Librarian]     Checking halyard-zsh/0.0.12 <https://forgeapi.puppetlabs.com>
[Librarian]       Resolved halyard-zsh (= 0.0.12) <https://forgeapi.puppetlabs.com> at halyard-zsh/0.0.12 <https://forgeapi.puppetlabs.com>
[Librarian]   Resolved halyard-zsh (= 0.0.12) <https://forgeapi.puppetlabs.com>
[Librarian] Conflict between halyard-homebrew (~> 2.0.0) <https://forgeapi.puppetlabs.com> and halyard-homebrew/1.13.3 <https://forgeapi.puppetlabs.com>
Could not resolve the dependencies.
/opt/halyard/vendor/ruby/2.0.0/gems/librarianp-0.6.3/lib/librarian/action/persist_resolution_mixin.rb:11:in `persist_resolution'
/opt/halyard/vendor/ruby/2.0.0/gems/librarianp-0.6.3/lib/librarian/action/resolve.rb:32:in `run'
/opt/halyard/vendor/ruby/2.0.0/gems/librarian-puppet-2.2.3/lib/librarian/puppet/action/resolve.rb:10:in `run'
/opt/halyard/vendor/ruby/2.0.0/gems/librarian-puppet-2.2.3/lib/librarian/puppet/cli.rb:104:in `resolve!'
/opt/halyard/vendor/ruby/2.0.0/gems/librarian-puppet-2.2.3/lib/librarian/puppet/cli.rb:68:in `install'
/opt/halyard/vendor/ruby/2.0.0/gems/thor-0.19.1/lib/thor/command.rb:27:in `run'
/opt/halyard/vendor/ruby/2.0.0/gems/thor-0.19.1/lib/thor/invocation.rb:126:in `invoke_command'
/opt/halyard/vendor/ruby/2.0.0/gems/thor-0.19.1/lib/thor.rb:359:in `dispatch'
/opt/halyard/vendor/ruby/2.0.0/gems/thor-0.19.1/lib/thor/base.rb:440:in `start'
/opt/halyard/vendor/ruby/2.0.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block (2 levels) in bin!'
/opt/halyard/vendor/ruby/2.0.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:31:in `returning_status'
/opt/halyard/vendor/ruby/2.0.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `block in bin!'
/opt/halyard/vendor/ruby/2.0.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:47:in `with_environment'
/opt/halyard/vendor/ruby/2.0.0/gems/librarianp-0.6.3/lib/librarian/cli.rb:26:in `bin!'
/opt/halyard/vendor/ruby/2.0.0/gems/librarian-puppet-2.2.3/bin/librarian-puppet:7:in `<top (required)>'
/opt/halyard/vendor/bin/librarian-puppet:17:in `load'
/opt/halyard/vendor/bin/librarian-puppet:17:in `<main>'
```

I'm probably missing something simple here...

**Comment by akerl** [comment]
Nope, this is a result of me having to revert the homebrew stuff after I boned up the licensing. Hoping to fix this soonish, but for now you could probably make it work using https://github.com/TheKevJames/puppet-homebrew

**Comment by akerl** [comment]
This should be overcome-by-circumstance now. I've rolled out v3 of halyard/puppet-homebrew, which is a fresh start w/ none of the "me-stealing-code" problems that I introduced in v2. It also only clones the brew repo to the local disk, so it's not particularly useful.

I'm currently doing a revamp of Halyard from the ground up, so the hope is that I'll add package installation to that repo soonish

**Comment by jaredledvina** [comment]
<3 Thanks!
