### ISSUE TITLE
Catalog application error with bundle

### ISSUE THREAD

**Issue by akerl** [halyard/halyard#136]
```
Less-MacBook:~ akerl$ halyard
Password:
/opt/halyard/vendor/ruby/2.4.0/gems/CFPropertyList-2.2.8/lib/cfpropertylist/rbCFTypes.rb:24: warning: constant ::Fixnum is deprecated
Notice: Compiled catalog for less-macbook.local in environment production in 0.75 seconds
Error: Failed to apply catalog: Execution of '/opt/brew/bin/brew list --full-name' returned 1: /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find rake-12.0.0 in any of the sources (Bundler::GemNotFound)
	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `map!'
	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/spec_set.rb:80:in `materialize'
	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/definition.rb:176:in `specs'
	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/definition.rb:235:in `specs_for'
	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/definition.rb:224:in `requested_specs'
	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/runtime.rb:118:in `block in definition_method'
	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/runtime.rb:19:in `setup'
	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler.rb:100:in `setup'
	from /opt/halyard/vendor/gems/bundler-1.14.6/lib/bundler/setup.rb:20:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
```

Smells like the prefetch in puppet-homebrew is failing

**Comment by akerl** [comment]
No longer encountering this
