### ISSUE TITLE
Could not find rake-12.3.2

### ISSUE THREAD

**Issue by double16** [halyard/halyard#172]
Using 10.14.3 clean with Xcode full install.

Steps to reproduce:
1. Run kickstart
2. Fork halyard/halyard
3. Edit Puppetfile to remove 'dev: true' and set mod 'halyard' to 0.0.35
4. sudo ./meta/puppet-run

2019-02-28 13:25:19 Admins-iMac.local STARTING RUN
2019-02-28 13:25:20 Admins-iMac.local /Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/spec_set.rb:87:in `block in materialize': Could not find rake-12.3.2 in any of the sources (Bundler::GemNotFound)
2019-02-28 13:25:20 Admins-iMac.local 	from /Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/spec_set.rb:81:in `map!'
2019-02-28 13:25:20 Admins-iMac.local 	from /Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/spec_set.rb:81:in `materialize'
2019-02-28 13:25:20 Admins-iMac.local 	from /Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/definition.rb:170:in `specs'
2019-02-28 13:25:20 Admins-iMac.local 	from /Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/definition.rb:237:in `specs_for'
2019-02-28 13:25:20 Admins-iMac.local 	from /Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/definition.rb:226:in `requested_specs'
2019-02-28 13:25:20 Admins-iMac.local 	from /Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:108:in `block in definition_method'
2019-02-28 13:25:20 Admins-iMac.local 	from /Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/runtime.rb:20:in `setup'
2019-02-28 13:25:20 Admins-iMac.local 	from /Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler.rb:107:in `setup'
2019-02-28 13:25:20 Admins-iMac.local 	from /Library/Ruby/Gems/2.3.0/gems/bundler-2.0.1/lib/bundler/setup.rb:20:in `<top (required)>'
2019-02-28 13:25:20 Admins-iMac.local 	from /opt/puppetlabs/puppet/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
2019-02-28 13:25:20 Admins-iMac.local 	from /opt/puppetlabs/puppet/lib/ruby/2.5.0/rubygems/core_ext/kernel_require.rb:59:in `require'
Admins-iMac

**Comment by akerl** [comment]
Sorry for the long delay in responding. I’ve fixed the issues that led to step 3 being necessary, and I’m not able to replicate the rake error you’re seeing.

Did you end up working around it or identifying the cause? I’m wondering if I fixed it since you opened this and didn’t realize.

**Comment by double16** [comment]
I hadn't been able to move on, but I'll update and try it today.

**Comment by double16** [comment]
Clean 10.14.4 install, Xcode and using your script from https://git.io/halyard. Same error.

**Comment by akerl** [comment]
I just did a totally fresh rebuild this morning (which is how I noticed this issue again). 10.4.4, fresh install from recovery mode.

A clarifying question: the end result of running `kickstart` is that it calls `puppet-run` on your behalf. Before, I thought you were saying that errored out due to the “dev: true” and version typo. Are you now seeing the rake error at the end of running `kickstart`, or do you get a different error / no error from that run?

Additionally: try just running `./meta/puppet-run` without sudo. It should prompt you for your password itself.

**Comment by double16** [comment]
Since you fixed the 'dev: true' and version typo, I decided to try the `kickstart` script. I started with a clean 10.14.4 VM + Xcode full, downloaded the script and ran. I got the same rake-12.3.2 not found error. I tried `./meta/puppet-run` just now and got the same error. Strange because rake-12.3.2 is there in /Library/Gems/2.3.0.

It's a little odd because Puppet is running Ruby 2.5.0 then calls out to the system Ruby which is 2.3.0. I'm not sure how mixing Ruby versions works.

Maybe the issue is I've got a full Xcode instead of only the command line tools. I could try rebuilding the VM without Xcode and let `kickstart` download everything. It'll take some time though, my network isn't very fast.

**Comment by akerl** [comment]
Interesting. I’ve not tried it w/ XCode installed first. But also, Puppet should never be calling out to system ruby. The reason for downloading the puppet bundle with its own ruby was to avoid the slew of errors like this that used to occur when I was trying to manage the system Ruby environment.

I just modified the script a moment ago so that the output of `bundle install` is printed during puppet-run.

I’m curious, is something installing ruby deps at the system level between the initial install and the kickstart? I’m wondering if Rake is somehow getting installed at the system level, causing the bundle install to skip it, but then the puppet run is failing to load the system Rake.

**Comment by double16** [comment]
I removed rake 12.3.2 from the system Ruby. I see different output. Bundler complains about running as root, installs rake 12.3.2, then proceeds. I ran `./meta/puppet-run` as a normal user.

**Comment by akerl** [comment]
Is anything else happening between the fresh Mojave install and running kickstart, other than installing XCode? I’ve just attempted that process, and wasn’t able to replicate the issue.

**Comment by double16** [comment]
I am doubting what I did when originally building the 10.14 VM. It got to 10.14.4 via upgrades. I'm going to start completely over.

**Comment by double16** [comment]
I rebuilt the VM, 10.14.4, no Xcode. I think it got past the rake error and now onto this:

Error while evaluating a Function Call, Class[Hostname]: expects a value for parameter 'hostname' (file: /opt/halyard/environments/production/manifests/site.pp, line: 2, column: 1) on node admins-imac.local

In /opt/halyard/repo/modules/hostname/manifests/init.pp, the hostname class has `$hostname` as it's first parameter. There is no default and site.pp is including it as `include 'hostname'`

**Comment by double16** [comment]
I see why I got the error, I need to fork and add an entry for my VM. Things are installing now. I'm curious if after a clean run, and installing full Xcode, if another run would fail.

**Comment by akerl** [comment]
👍 

The hostname info is my bad; I’m not quite sure how the hostname module should handle that, whether there should be a “default” hostname of “mac” or something, or if it should just skip setting the hostname if it’s not set in hiera.

**Comment by akerl** [comment]
Opened https://github.com/halyard/puppet-hostname/issues/7 To track that

**Comment by double16** [comment]
I installed the full Xcode and tried running again, and it's going. I must have done something in my previous VM that I can't remember.
